---
- name: 0. Remove MySQL
  apt:
          name: mysql-client
          state: absent

  
- name: 1. Install MariaDB server package
  apt:
          name: mariadb-server
          state: present

- name: 2. Start Mysql Service
  service:
          name: mysql
          state: started 
          enabled: true
- name: Install Python3 PIP
  apt:
          name: python3-pip
          state: latest

- name: Install python Mysql package #required for mysql_db tasks
  pip:
          executable: pip3
          name: PyMySQL 
          state: latest

